# Generated by Django 3.1 on 2020-10-16 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuto',
            fields=[
                ('cle_tuto', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('typeTuto', models.CharField(max_length=50)),
                ('lien_url', models.CharField(max_length=700)),
                ('client_url', models.CharField(default='', max_length=700)),
                ('clientName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tuto',
            },
        ),
    ]
