# Generated by Django 3.1 on 2020-10-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuto',
            old_name='lien_url',
            new_name='idTutoVideo',
        ),
    ]
